"""connector state

Revision ID: 6bf9aa68a23f
Revises: a0f728e4421a
Create Date: 2026-07-11 12:47:51.349411

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '6bf9aa68a23f'
down_revision = 'a0f728e4421a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_connections',
    sa.Column('engagement_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connector_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('instance_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_sync_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_preview_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_applied_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('engagement_id', 'connector_type')
    )
    op.create_table('connector_field_mappings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engagement_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connector_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stream_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_field_mappings_engagement_id'), 'connector_field_mappings', ['engagement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connector_field_mappings_engagement_id'), table_name='connector_field_mappings')
    op.drop_table('connector_field_mappings')
    op.drop_table('connector_connections')
    # ### end Alembic commands ###
