"""drop dead engagements.current_step

Revision ID: a0f728e4421a
Revises: daa6408d5d07
Create Date: 2026-07-11 12:42:09.031483

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'a0f728e4421a'
down_revision = 'daa6408d5d07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagements', 'current_step')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'engagements',
        sa.Column(
            'current_step',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            server_default='streams',  # populated rows need a value on downgrade
        ),
    )
    # ### end Alembic commands ###
