"""audit events

Revision ID: daa6408d5d07
Revises: fe20c1b639a4
Create Date: 2026-07-10 13:31:23.773564

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision = 'daa6408d5d07'
down_revision = 'fe20c1b639a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artefact_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artefact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engagement_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_engagement_id'), 'audit_events', ['engagement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_engagement_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
