"""initial schema

Revision ID: fe20c1b639a4
Revises: 
Create Date: 2026-07-10 13:23:51.884155

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision = 'fe20c1b639a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagements',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_comments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engagement_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stream_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('function_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_comments_engagement_id'), 'process_comments', ['engagement_id'], unique=False)
    op.create_table('process_states',
    sa.Column('engagement_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stream_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bpmn_xml', sa.Text(), nullable=True),
    sa.Column('element_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('engagement_id', 'stream_type')
    )
    op.create_table('teleology_rows',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engagement_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stream_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('function_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ambitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('org_ambitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teleology_rows_engagement_id'), 'teleology_rows', ['engagement_id'], unique=False)
    op.create_table('value_streams',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engagement_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('baseline_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('baseline_loaded', sa.Boolean(), nullable=False),
    sa.Column('approval_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_value_streams_engagement_id'), 'value_streams', ['engagement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_value_streams_engagement_id'), table_name='value_streams')
    op.drop_table('value_streams')
    op.drop_index(op.f('ix_teleology_rows_engagement_id'), table_name='teleology_rows')
    op.drop_table('teleology_rows')
    op.drop_table('process_states')
    op.drop_index(op.f('ix_process_comments_engagement_id'), table_name='process_comments')
    op.drop_table('process_comments')
    op.drop_table('engagements')
    # ### end Alembic commands ###
